// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRP6X9BhxcOBKlmjQW4p9COrhjHWFHjTg',
    appId: '1:163763635061:web:d1935cab29e2d67d2b493c',
    messagingSenderId: '163763635061',
    projectId: 'ams-finals',
    authDomain: 'ams-finals.firebaseapp.com',
    storageBucket: 'ams-finals.firebasestorage.app',
    measurementId: 'G-QPYRGEPFZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgRJRFlzUw7rryKxuNAz0Oy0Wt0_0LWKg',
    appId: '1:163763635061:android:14cd6261710062c02b493c',
    messagingSenderId: '163763635061',
    projectId: 'ams-finals',
    storageBucket: 'ams-finals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADVkq0zp7FlnrQqrvpt0f39mYPQZl9sPA',
    appId: '1:163763635061:ios:af818af602c530242b493c',
    messagingSenderId: '163763635061',
    projectId: 'ams-finals',
    storageBucket: 'ams-finals.firebasestorage.app',
    iosBundleId: 'com.example.flutterproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADVkq0zp7FlnrQqrvpt0f39mYPQZl9sPA',
    appId: '1:163763635061:ios:af818af602c530242b493c',
    messagingSenderId: '163763635061',
    projectId: 'ams-finals',
    storageBucket: 'ams-finals.firebasestorage.app',
    iosBundleId: 'com.example.flutterproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRP6X9BhxcOBKlmjQW4p9COrhjHWFHjTg',
    appId: '1:163763635061:web:bebe2fbd15ff58102b493c',
    messagingSenderId: '163763635061',
    projectId: 'ams-finals',
    authDomain: 'ams-finals.firebaseapp.com',
    storageBucket: 'ams-finals.firebasestorage.app',
    measurementId: 'G-G72XCPGSR7',
  );
}
